<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7LdcGpr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7LdcGpr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7LdcGpr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7LdcGpr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7LdcGpr\App_KernelDevDebugContainer([
    'container.build_hash' => '7LdcGpr',
    'container.build_id' => 'e73178fd',
    'container.build_time' => 1577051466,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7LdcGpr');
